name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: install
        run: |
          make install
      - name: lint
        run: make lint
      # - name: mypy
      #   run: make mypy
  
  test:
    name: test py${{ matrix.python }} on linux
    runs-on: {{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.7', '3.8', '3.9', '3.10']
    
    steps:
    - uses: actions/checkout@v3

    - name: set up python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}

    - name: install
      run: |
        make install
    
    - name: test
      run: |
        make test

    
