name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Lint
        run: make lint

      - name: Pyright
        run: make pyright

  test:
    name: test py${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.8'
            os: windows-latest
          - python-version: '3.9'
            os: macos-latest
          - python-version: '3.10'
            os: ubuntu-latest
          - python-version: '3.11'
            os: ubuntu-latest
          - python-version: '3.11'
            os: windows-latest
          - python-version: '3.11'
            os: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: test
        run: |
          make test

  deploy:
    needs: test
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Build
        run: |
          poetry build

      - name: Publish
        run: |
          poetry publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
